# Generated by Django 6.0.7 on 2026-08-04 14:01

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='devotional',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='leadership',
            name='biography',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='biography'),
        ),
        migrations.AlterField(
            model_name='ministry',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='sermon',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='testimony',
            name='story',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='story'),
        ),
    ]
