# Generated by Django 6.0.7 on 2026-08-11 10:52

import core.imgbb_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_announcement_content_alter_devotional_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='churchsettings',
            name='favicon',
            field=models.ImageField(blank=True, null=True, storage=core.imgbb_storage.ImgBBStorage(), upload_to='settings/', verbose_name='favicon'),
        ),
        migrations.AlterField(
            model_name='churchsettings',
            name='hero_default_image',
            field=models.ImageField(blank=True, null=True, storage=core.imgbb_storage.ImgBBStorage(), upload_to='settings/', verbose_name='default hero image'),
        ),
        migrations.AlterField(
            model_name='churchsettings',
            name='logo',
            field=models.ImageField(blank=True, null=True, storage=core.imgbb_storage.ImgBBStorage(), upload_to='settings/', verbose_name='logo'),
        ),
        migrations.AlterField(
            model_name='devotional',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, storage=core.imgbb_storage.ImgBBStorage(), upload_to='devotionals/', verbose_name='featured image'),
        ),
        migrations.AlterField(
            model_name='devotional',
            name='og_image',
            field=models.ImageField(blank=True, null=True, storage=core.imgbb_storage.ImgBBStorage(), upload_to='seo/', verbose_name='Open Graph image'),
        ),
        migrations.AlterField(
            model_name='event',
            name='banner',
            field=models.ImageField(blank=True, null=True, storage=core.imgbb_storage.ImgBBStorage(), upload_to='events/', verbose_name='banner'),
        ),
        migrations.AlterField(
            model_name='event',
            name='og_image',
            field=models.ImageField(blank=True, null=True, storage=core.imgbb_storage.ImgBBStorage(), upload_to='seo/', verbose_name='Open Graph image'),
        ),
        migrations.AlterField(
            model_name='galleryalbum',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, storage=core.imgbb_storage.ImgBBStorage(), upload_to='gallery/covers/', verbose_name='cover image'),
        ),
        migrations.AlterField(
            model_name='galleryalbum',
            name='og_image',
            field=models.ImageField(blank=True, null=True, storage=core.imgbb_storage.ImgBBStorage(), upload_to='seo/', verbose_name='Open Graph image'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(storage=core.imgbb_storage.ImgBBStorage(), upload_to='gallery/images/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='givinginformation',
            name='qr_image',
            field=models.ImageField(blank=True, null=True, storage=core.imgbb_storage.ImgBBStorage(), upload_to='giving/qr/', verbose_name='QR image'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='image',
            field=models.ImageField(storage=core.imgbb_storage.ImgBBStorage(), upload_to='hero/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='leadership',
            name='og_image',
            field=models.ImageField(blank=True, null=True, storage=core.imgbb_storage.ImgBBStorage(), upload_to='seo/', verbose_name='Open Graph image'),
        ),
        migrations.AlterField(
            model_name='leadership',
            name='photo',
            field=models.ImageField(blank=True, null=True, storage=core.imgbb_storage.ImgBBStorage(), upload_to='leadership/', verbose_name='photo'),
        ),
        migrations.AlterField(
            model_name='ministry',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=core.imgbb_storage.ImgBBStorage(), upload_to='ministries/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='ministry',
            name='og_image',
            field=models.ImageField(blank=True, null=True, storage=core.imgbb_storage.ImgBBStorage(), upload_to='seo/', verbose_name='Open Graph image'),
        ),
        migrations.AlterField(
            model_name='sermon',
            name='og_image',
            field=models.ImageField(blank=True, null=True, storage=core.imgbb_storage.ImgBBStorage(), upload_to='seo/', verbose_name='Open Graph image'),
        ),
        migrations.AlterField(
            model_name='sermon',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, storage=core.imgbb_storage.ImgBBStorage(), upload_to='sermons/thumbnails/', verbose_name='thumbnail'),
        ),
        migrations.AlterField(
            model_name='testimony',
            name='og_image',
            field=models.ImageField(blank=True, null=True, storage=core.imgbb_storage.ImgBBStorage(), upload_to='seo/', verbose_name='Open Graph image'),
        ),
        migrations.AlterField(
            model_name='testimony',
            name='photo',
            field=models.ImageField(blank=True, null=True, storage=core.imgbb_storage.ImgBBStorage(), upload_to='testimonies/', verbose_name='photo'),
        ),
    ]
