# Generated by Django 6.0.7 on 2026-08-15 13:09

import core.imgbb_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_churchsettings_favicon_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryalbum',
            name='canonical_url',
        ),
        migrations.RemoveField(
            model_name='galleryalbum',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='galleryalbum',
            name='meta_keywords',
        ),
        migrations.RemoveField(
            model_name='galleryalbum',
            name='meta_title',
        ),
        migrations.RemoveField(
            model_name='galleryalbum',
            name='og_image',
        ),
        migrations.RemoveField(
            model_name='galleryalbum',
            name='slug',
        ),
        migrations.AlterField(
            model_name='galleryalbum',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, storage=core.imgbb_storage.ImgBBStorage(), upload_to='gallery/albums/', verbose_name='cover image'),
        ),
    ]
