"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-)v9bow6z^@*3c3ulic2ub5^cmp9zlpnp%b&*)w5$$k_!-8!$!!'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []
                        

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "core",
    "django_ckeditor_5",
    'jazzmin',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        "DIRS": [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]
CKEDITOR_5_CONFIGS = {
    "extends": {
        "toolbar": [
            "heading",
            "|",
            "bold",
            "italic",
            "underline",
            "strikethrough",
            "|",
            "bulletedList",
            "numberedList",
            "|",
            "alignment",
            "blockQuote",
            "link",
            "insertTable",
            "|",
            "undo",
            "redo",
        ],
    },
}
JAZZMIN_SETTINGS = {
    "site_title": "EGWM CMS",
    "site_header": "Embassy of God's Word Ministry",
    "site_brand": "EGWM CMS",
    "welcome_sign": "Welcome to EGWM Admin",
    "copyright": "Embassy of God's Word Ministry",
    "show_sidebar": True,
    "navigation_expanded": True,
    "order_with_respect_to": [
        "core.Leadership",
        "core.Devotional",
        "core.Event",
        "core.Sermon",
        "core.Ministry",
        "core.GalleryAlbum",
        "core.Testimony",
        "core.ContactMessage",
        "core.PrayerRequest",
        "core.NewsletterSubscriber",
        "core.ChurchSettings",
    ],
    "icons": {
        "core.Leadership": "fas fa-user-tie",
        "core.Devotional": "fas fa-book-bible",
        "core.Event": "fas fa-calendar-days",
        "core.Sermon": "fas fa-microphone",
        "core.Ministry": "fas fa-people-group",
        "core.GalleryAlbum": "fas fa-images",
        "core.Testimony": "fas fa-comments",
        "core.ContactMessage": "fas fa-envelope",
        "core.PrayerRequest": "fas fa-hands-praying",
        "core.NewsletterSubscriber": "fas fa-paper-plane",
        "core.ChurchSettings": "fas fa-gear",
    },
}
JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,

    "brand_colour": "navbar-dark",
    "accent": "accent-warning",

    "navbar": "navbar-dark",
    "no_navbar_border": False,

    "sidebar": "sidebar-dark-primary",

    "theme": "darkly",

    "button_classes": {
        "primary": "btn-warning",
        "secondary": "btn-secondary",
        "success": "btn-success",
        "danger": "btn-danger",
        "warning": "btn-warning",
        "info": "btn-info",
    }
}
# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

STATICFILES_DIRS = [
    BASE_DIR / "static",
]
LOGIN_URL = "/admin/login/"
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"